import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import RootProvider from "@/context/provider/root-reducer";
import { ModalContextProvider } from "@/lib/utils/ModalContext";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Relief Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <AuthProvider>
          <RootProvider>
            <ModalContextProvider>{children}</ModalContextProvider>
          </RootProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
